# Nome do seu pipeline de Integração Contínua
name: CI com Java 21 e Maven

# Gatilhos: roda o pipeline em pushes e pull requests para a branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Nome do job, pode ser qualquer um
  build-e-test:

    # A máquina virtual que será usada
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do seu código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java, especificando a versão do seu projeto
      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          # A linha mais importante: deve ser IGUAL à versão do seu projeto
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Adiciona cache para acelerar builds futuros

      # 3. Executa o build e os testes com o Maven
      - name: Build e Testes com Maven
        # O comando "package" primeiro compila e RODA OS TESTES.
        # Se os testes falharem, o pipeline para aqui.
        run: mvn -B package --file pom.xml
